network:
  bridges:
    br0:
      addresses:
      - STATIC_IP_ADDRESS/21
      dhcp4: true
      interfaces:
      - wan
      - lan3
    br1:
      addresses:
      - 192.168.2.1/24
      - 192.168.2.2/24
      dhcp4: false
      interfaces:
      - lan0
      - lan1
      - lan2
  ethernets:
    eth0:
      dhcp4: false
    eth1:
      dhcp4: false
    lan0:
      dhcp4: false
    lan1:
      dhcp4: false
    lan2:
      dhcp4: false
    lan3:
      dhcp4: false
    wan:
      dhcp4: false
  renderer: networkd
  version: 2

